version: 1.0.{build}
image: Visual Studio 2017

environment:
  cert_store: Cert:\CurrentUser\My
  cert_password:
    secure: DtOAA160sv4uOE2DYCr+QPAM+XLGKd/Z08cf/2nAQ4g=

branches:
  only:
    - build

shallow_clone: true

configuration: Release

build:
  parallel: true 
  project: RetriX.sln

#before_build:
#  - ps: $pwd = ConvertTo-SecureString -String "$env:cert_password" -AsPlainText -Force
#  - ps: $env:cert_thumbprint = (Import-PfxCertificate -FilePath ".\RetriX.UWP\SigningCert_Release.pfx" -CertStoreLocation "$env:cert_store" -Password $pwd).Thumbprint
#  - ps: $pwd = $null
#  - ps: echo "Imported signing certificate. Thumbprint is $env:cert_thumbprint"

#after_build:
#  - ps: Remove-Item -Path ("{0}\{1}" -f $env:cert_store, $env:cert_thumbprint)