version: 2.1.{build}.0
image: Visual Studio 2017

environment:
  cert_store: Cert:\CurrentUser\My
  cert_password:
    secure: DtOAA160sv4uOE2DYCr+QPAM+XLGKd/Z08cf/2nAQ4g=

branches:
  only:
    - build

shallow_clone: true

configuration: Release

#before_build:
#  - ps: $pwd = ConvertTo-SecureString -String "$env:cert_password" -AsPlainText -Force
#  - ps: $env:cert_thumbprint = (Import-PfxCertificate -FilePath ".\RetriX.UWP\SigningCert_Release.pfx" -CertStoreLocation "$env:cert_store" -Password $pwd).Thumbprint
#  - ps: $pwd = $null
#  - ps: echo "Imported signing certificate. Thumbprint is $env:cert_thumbprint"

build_script:
  - ps: nuget restore
  - cmd: msbuild RetriX.UWP\Retrix.UWP.csproj /p:Configuration=%configuration%;Platform=x86;AppxBundle=Always;AppxBundlePlatforms="x86|x64|ARM"
  - ps: signtool sign /fd SHA256 /f RetriX.UWP\SigningCert_Release.pfx /p ${env:cert_password} /tr http://tsa.startssl.com/rfc3161 RetriX.UWP\AppPackages\Retrix.UWP_${env:version}_Test\Retrix.UWP_${env:version}_x86_x64_ARM.appxbundle

#after_build:
#  - ps: Remove-Item -Path ("{0}\{1}" -f $env:cert_store, $env:cert_thumbprint)

artifacts:
  - path: 'RetriX.UWP\AppPackages\**\*.appxbundle'
  - path: 'RetriX.UWP\AppPackages\**\*.appx'