version: 1.0.{build}
image: Visual Studio 2017

environment:
  cert_store: Cert:\CurrentUser\My
  cert_password:
    secure: JxTdA0Qblwql3thdV4h3jVSWfMCQgmjKPoBZgEiLMOs=

branches:
  only:
    - build

shallow_clone: true

configuration: Release

build:
  parallel: true 
  project: RetriX.sln

before_build:
  - ps: $env:cert_thumbprint = (Import-PfxCertificate -FilePath SigningCertificate.pfx -CertStoreLocation "$env:cert_store" -Password (ConvertTo-SecureString -String "$env:cert_password" -AsPlainText -Force)).Thumbprint
  - ps: echo "Imported signing certificate. Thumbprint is $env:cert_thumbprint"

after_build:
  - ps: Remove-Item -Path ("{0}\{1}" -f $env:cert_store, $env:cert_thumbprint)