version: 2.1.{build}.0
image: Visual Studio 2017

environment:
  appx_manifest_path: "Retrix.UWP\\Package.appxmanifest"
  appx_project_path: "Retrix.UWP\\RetriX.UWP.csproj"
  cert_password:
    secure: JjPBLfMO/rsSFxtpY/FXyfduELdRu7Srmp/60D2GCGI=

branches:
  only:
    - build

shallow_clone: true

configuration: Release

before_build:
  - ps: '$cert = (Import-PfxCertificate -FilePath ".\RetriX.UWP\SigningCert_Release.pfx" -Password (ConvertTo-SecureString -String "$env:cert_password" -AsPlainText -Force) -CertStoreLocation "Cert:\CurrentUser\My\").Thumbprint'
  - ps: '$cert_thumbprint = "$cert.Thumbprint"; $cert_subject = "$cert.Subject"; $cert=$null'
  - ps: 'echo $cert_subject'
  - ps: '[xml]$manifest = Get-Content "$env:appx_manifest_path"; $manifest.Package.Identity.Publisher="$env:cert_subject"; $manifest.Save("$pwd\$env:appx_manifest_path")'
  - ps: '[xml]$projfile = Get-Content "$env:appx_project_path"; $projfile.Project.PropertyGroup[0].PackageCertificateKeyFile = "";  $projfile.Project.PropertyGroup[0].PackageCertificateThumbprint = "$env:cert_thumbprint"; $projfile.Save("$pwd\$env:appx_project_path")'

build_script:
#  - ps: '[xml]$proj_xml=Get-Content .\RetriX.UWP\RetriX.UWP.csproj;$target_sdk_ver=$proj_xml.Project.PropertyGroup[0].TargetPlatformVersion.ChildNodes[0].Data'
#  - ps: '&"${env:ProgramFiles(x86)}\Windows Kits\10\bin\$target_sdk_ver\x86\signtool.exe" sign /fd SHA256 /f RetriX.UWP\SigningCert_Release.pfx /p ${env:cert_password} /tr http://timestamp.comodoca.com /td SHA256 RetriX.UWP\AppPackages\Retrix.UWP_${env:appveyor_build_version}_Test\Retrix.UWP_${env:appveyor_build_version}_x86_x64_ARM.appxbundle'
  - ps: '[xml]$manifest = Get-Content "$env:appx_manifest_path"; $manifest.Package.Identity.Version="$env:appveyor_build_version"; $manifest.Save("$pwd\$env:appx_manifest_path")'
  - ps: '&nuget restore'
  - cmd: 'msbuild RetriX.UWP\Retrix.UWP.csproj /p:Configuration=%configuration%;Platform=x86;AppxBundle=Always;AppxBundlePlatforms="x86|x64|ARM"'
#  - ps: '&"${env:ProgramFiles(x86)}\Windows Kits\10\bin\$target_sdk_ver\x86\signtool.exe" sign /fd SHA256 /f RetriX.UWP\SigningCert_Release.pfx /p ${env:cert_password} /tr http://timestamp.comodoca.com /td SHA256 RetriX.UWP\AppPackages\Retrix.UWP_${env:appveyor_build_version}_Test\Retrix.UWP_${env:appveyor_build_version}_x86_x64_ARM.appxbundle'

artifacts:
  - path: 'RetriX.UWP\AppPackages\**\*.appxbundle'
  - path: 'RetriX.UWP\AppPackages\**\*.appx'