version: 2.1.{build}.0
image: Visual Studio 2017

environment:
  cert_password:
    secure: jqsEh3FCK0/rF+3rBWxTY135zB/nlwX6yovv/PYAx0Q=

branches:
  only:
    - build

shallow_clone: true

configuration: Release

build_script:
  - ps: echo ${env:cert_password}
  - ps: '&"${env:ProgramFiles(x86)}\Windows Kits\10\bin\$target_sdk_ver\x86\signtool.exe" sign /fd SHA256 /f "RetriX.UWP\SigningCert_Release.pfx" /p "${env:cert_password}" "somefile.appxbundle"'
  - ps: '[xml]$manifest = Get-Content "Retrix.UWP\Package.appxmanifest";$manifest.Package.Identity.Version="$env:appveyor_build_version";$manifest.Save("$pwd\Retrix.UWP\Package.appxmanifest")'
  - ps: '&nuget restore'
  - cmd: 'msbuild RetriX.UWP\Retrix.UWP.csproj /p:Configuration=%configuration%;Platform=x86;AppxBundle=Always;AppxBundlePlatforms="x86|x64|ARM"'
  - ps: '[xml]$proj_xml=Get-Content .\RetriX.UWP\RetriX.UWP.csproj;$target_sdk_ver=$proj_xml.Project.PropertyGroup[0].TargetPlatformVersion.ChildNodes[0].Data'
  - ps: '&"${env:ProgramFiles(x86)}\Windows Kits\10\bin\$target_sdk_ver\x86\signtool.exe" sign /fd SHA256 /f RetriX.UWP\SigningCert_Release.pfx /p ${env:cert_password} /tr http://timestamp.comodoca.com /td SHA256 RetriX.UWP\AppPackages\Retrix.UWP_${env:appveyor_build_version}_Test\Retrix.UWP_${env:appveyor_build_version}_x86_x64_ARM.appxbundle'

artifacts:
  - path: 'RetriX.UWP\AppPackages\**\*.appxbundle'
  - path: 'RetriX.UWP\AppPackages\**\*.appx'