//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetriX.Shared.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetriX.Shared.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file supplied is not the expected one. Try a different file..
        /// </summary>
        internal static string FileHashMismatchMessage {
            get {
                return ResourceManager.GetString("FileHashMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file.
        /// </summary>
        internal static string FileHashMismatchTitle {
            get {
                return ResourceManager.GetString("FileHashMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the game.
        ///The game file may be corrupt or in a wrong format: try another one..
        /// </summary>
        internal static string GameLoadingFailAlertMessage {
            get {
                return ResourceManager.GetString("GameLoadingFailAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load game.
        /// </summary>
        internal static string GameLoadingFailAlertTitle {
            get {
                return ResourceManager.GetString("GameLoadingFailAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while running the game.
        ///Restart RetriX and try again..
        /// </summary>
        internal static string GameRunningFailAlertMessage {
            get {
                return ResourceManager.GetString("GameRunningFailAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game runtime error.
        /// </summary>
        internal static string GameRunningFailAlertTitle {
            get {
                return ResourceManager.GetString("GameRunningFailAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandai.
        /// </summary>
        internal static string ManufacturerNameBandai {
            get {
                return ResourceManager.GetString("ManufacturerNameBandai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalBurn Alpha.
        /// </summary>
        internal static string ManufacturerNameFBAlpha {
            get {
                return ResourceManager.GetString("ManufacturerNameFBAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEC.
        /// </summary>
        internal static string ManufacturerNameNEC {
            get {
                return ResourceManager.GetString("ManufacturerNameNEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo.
        /// </summary>
        internal static string ManufacturerNameNintendo {
            get {
                return ResourceManager.GetString("ManufacturerNameNintendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGA.
        /// </summary>
        internal static string ManufacturerNameSega {
            get {
                return ResourceManager.GetString("ManufacturerNameSega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNK.
        /// </summary>
        internal static string ManufacturerNameSNK {
            get {
                return ResourceManager.GetString("ManufacturerNameSNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sony.
        /// </summary>
        internal static string ManufacturerNameSony {
            get {
                return ResourceManager.GetString("ManufacturerNameSony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected does not contain the game file you are trying to open. Try again..
        /// </summary>
        internal static string SelectFolderInvalidAlertMessage {
            get {
                return ResourceManager.GetString("SelectFolderInvalidAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        internal static string SelectFolderInvalidAlertTitle {
            get {
                return ResourceManager.GetString("SelectFolderInvalidAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is made up of multiple files. Please select the folder that contains them to load it..
        /// </summary>
        internal static string SelectFolderRequestAlertMessage {
            get {
                return ResourceManager.GetString("SelectFolderRequestAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game folder.
        /// </summary>
        internal static string SelectFolderRequestAlertTitle {
            get {
                return ResourceManager.GetString("SelectFolderRequestAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game state saved to slot {0}.
        /// </summary>
        internal static string StateSavedToSlotMessageBody {
            get {
                return ResourceManager.GetString("StateSavedToSlotMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State saved.
        /// </summary>
        internal static string StateSavedToSlotMessageTitle {
            get {
                return ResourceManager.GetString("StateSavedToSlotMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade.
        /// </summary>
        internal static string SystemNameArcade {
            get {
                return ResourceManager.GetString("SystemNameArcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS.
        /// </summary>
        internal static string SystemNameDS {
            get {
                return ResourceManager.GetString("SystemNameDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Color.
        /// </summary>
        internal static string SystemNameGameBoy {
            get {
                return ResourceManager.GetString("SystemNameGameBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Advance.
        /// </summary>
        internal static string SystemNameGameBoyAdvance {
            get {
                return ResourceManager.GetString("SystemNameGameBoyAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Gear.
        /// </summary>
        internal static string SystemNameGameGear {
            get {
                return ResourceManager.GetString("SystemNameGameGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master System.
        /// </summary>
        internal static string SystemNameMasterSystem {
            get {
                return ResourceManager.GetString("SystemNameMasterSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega CD.
        /// </summary>
        internal static string SystemNameMegaCD {
            get {
                return ResourceManager.GetString("SystemNameMegaCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega Drive.
        /// </summary>
        internal static string SystemNameMegaDrive {
            get {
                return ResourceManager.GetString("SystemNameMegaDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo Geo.
        /// </summary>
        internal static string SystemNameNeoGeo {
            get {
                return ResourceManager.GetString("SystemNameNeoGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo Geo Pocket Color.
        /// </summary>
        internal static string SystemNameNeoGeoPocket {
            get {
                return ResourceManager.GetString("SystemNameNeoGeoPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES.
        /// </summary>
        internal static string SystemNameNES {
            get {
                return ResourceManager.GetString("SystemNameNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo 64.
        /// </summary>
        internal static string SystemNameNintendo64 {
            get {
                return ResourceManager.GetString("SystemNameNintendo64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Engine.
        /// </summary>
        internal static string SystemNamePCEngine {
            get {
                return ResourceManager.GetString("SystemNamePCEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Engine CD.
        /// </summary>
        internal static string SystemNamePCEngineCD {
            get {
                return ResourceManager.GetString("SystemNamePCEngineCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-FX.
        /// </summary>
        internal static string SystemNamePCFX {
            get {
                return ResourceManager.GetString("SystemNamePCFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation.
        /// </summary>
        internal static string SystemNamePlayStation {
            get {
                return ResourceManager.GetString("SystemNamePlayStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        internal static string SystemNameSaturn {
            get {
                return ResourceManager.GetString("SystemNameSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG-1000.
        /// </summary>
        internal static string SystemNameSG1000 {
            get {
                return ResourceManager.GetString("SystemNameSG1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Nintendo.
        /// </summary>
        internal static string SystemNameSNES {
            get {
                return ResourceManager.GetString("SystemNameSNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WonderSwan Color.
        /// </summary>
        internal static string SystemNameWonderSwan {
            get {
                return ResourceManager.GetString("SystemNameWonderSwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files required to run this game are missing. Install them using the settings page and try again..
        /// </summary>
        internal static string SystemUnmetDependenciesAlertMessage {
            get {
                return ResourceManager.GetString("SystemUnmetDependenciesAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required files missing.
        /// </summary>
        internal static string SystemUnmetDependenciesAlertTitle {
            get {
                return ResourceManager.GetString("SystemUnmetDependenciesAlertTitle", resourceCulture);
            }
        }
    }
}
